# Generated by Django 3.0.7 on 2020-10-13 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50)),
                ('furniture', models.CharField(max_length=100)),
                ('position_x', models.IntegerField(help_text='value in pixels')),
                ('position_y', models.IntegerField(help_text='value in pixels')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('pgroups', models.ManyToManyField(to='whereisit_app.GroupOfUsers')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='def-item.png', upload_to='items_pics')),
                ('category', models.CharField(choices=[('Tools', 'Tools'), ('Books', 'Books'), ('Computer stuff', 'Computer stuff'), ('Clothes', 'Clothes'), ('Kitchen', 'Kitchen'), ('Bedclothes', 'Bedclothes'), ('Holidays', 'Holidays'), ('Bathroom', 'Bathroom'), ('Car stuff', 'Car stuff'), ('Toys', 'Toys'), ('Board games', 'Board games'), ('Other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_borrowed', models.BooleanField(blank=True, default=False)),
                ('who_borrowed', models.CharField(blank=True, default='', max_length=30, verbose_name='If yes, who has borrowed it:')),
                ('when_borrowed', models.DateTimeField(blank=True, null=True, verbose_name='If yes, then when was that(YYYY-MM-DD):')),
                ('groups', models.ManyToManyField(to='whereisit_app.GroupOfUsers')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whereisit_app.Location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
