# Generated by Django 3.0.7 on 2020-07-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whereisit_app', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('T', 'Tools'), ('Cl', 'Clothes'), ('K', 'Kitchen'), ('Bc', 'Bedclothes'), ('H', 'Holidays'), ('Bt', 'Bathroom'), ('Car', 'Car stuff'), ('O', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_borrowed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
