# Generated by Django 3.0.7 on 2020-07-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whereisit_app', '0003_auto_20200707_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='when_borrowed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
