# Generated by Django 3.0.7 on 2020-07-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whereisit_app', '0007_auto_20200707_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Tools', 'Tools'), ('Computer stuff', 'Computer stuff'), ('Clothes', 'Clothes'), ('Kitchen', 'Kitchen'), ('Bedclothes', 'Bedclothes'), ('Holidays', 'Holidays'), ('Bathroom', 'Bathroom'), ('Car_stuff', 'Car stuff'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
