# Generated by Django 3.0.7 on 2020-07-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whereisit_app', '0008_auto_20200709_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='def-item.png', upload_to='items_pics'),
        ),
    ]
