# Generated by Django 3.0.7 on 2020-07-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whereisit_app', '0009_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='days_passed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
