# Generated by Django 3.0.7 on 2020-07-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whereisit_app', '0010_item_days_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='days_passed',
        ),
    ]
