from .models import GroupOfUsers, User, Item, Location


def basic_setup():
    print("***basic_setup initialized***")

    rodzice = GroupOfUsers.objects.create(name='Rodzice')
    rodzice.save()
    dzieci = GroupOfUsers.objects.create(name='Dzieci')
    dzieci.save()

    user1 = User.objects.create(username='elener', email='elener@wp.pl')
    user1.set_password('testing666')
    user1.u_groups.add(rodzice)
    user1.u_groups.add(dzieci)
    user1.save()
    user2 = User.objects.create(username='norbi', email='norbi@wp.pl')
    user2.set_password('testing666')
    user2.u_groups.add(rodzice)
    user2.save()
    user3 = User.objects.create(username='ala', email='ala@wp.pl')
    user3.set_password('testing666')
    user3.u_groups.add(dzieci)
    user3.save()

    location1 = Location.objects.create(room='Salon', furniture='Regał Billy 1', position_x='300', position_y='395')
    location1.save()
    location2 = Location.objects.create(room='Salon', furniture='Regał Billy 2', position_x='385', position_y='395')
    location2.save()
    location3 = Location.objects.create(room='Salon', furniture='Regał Billy 3', position_x='472', position_y='395')
    location3.save()
    location4 = Location.objects.create(room='Salon', furniture='Regał Billy 4', position_x='557', position_y='395')
    location4.save()
    location5 = Location.objects.create(room='Salon', furniture='Regał Billy 5', position_x='642', position_y='395')
    location5.save()
    location6 = Location.objects.create(room='Salon', furniture='Sofa', position_x='550', position_y='292')
    location6.save()
    location7 = Location.objects.create(room='Kuchnia', furniture='1 szafka od komina', position_x='62', position_y='545')
    location7.save()
    location8 = Location.objects.create(room='Kuchnia', furniture='2 szafka od komina', position_x='62', position_y='507')
    location8.save()
    location9 = Location.objects.create(room='Kuchnia', furniture='3 szafka od komina', position_x='62', position_y='468')
    location9.save()
    location10 = Location.objects.create(room='Kuchnia', furniture='4 szafka od komina', position_x='62', position_y='418')
    location10.save()
    location11 = Location.objects.create(room='Kuchnia', furniture='5 szafka od komina', position_x='62', position_y='360')
    location11.save()
    location12 = Location.objects.create(room='Kuchnia', furniture='6 szafka od komina', position_x='62', position_y='298')
    location12.save()
    location13 = Location.objects.create(room='Kuchnia', furniture='7 szafka od komina', position_x='62', position_y='240')
    location13.save()
    location14 = Location.objects.create(room='Kuchnia', furniture='8 szafka od komina', position_x='62', position_y='190')
    location14.save()
    location15 = Location.objects.create(room='Korytarz', furniture='Szafa cz.prawa', position_x='64', position_y='646')
    location15.save()
    location16 = Location.objects.create(room='Korytarz', furniture='Szafa cz.środkowa', position_x='64', position_y='726')
    location16.save()
    location17 = Location.objects.create(room='Korytarz', furniture='Szafa cz.lewa', position_x='64', position_y='806')
    location17.save()
    location18 = Location.objects.create(room='Gościnny', furniture='Szafa cz.prawa', position_x='280', position_y='663')
    location18.save()
    location19 = Location.objects.create(room='Gościnny', furniture='Szafa cz.lewa', position_x='360', position_y='663')
    location19.save()
    location20 = Location.objects.create(room='Gościnny', furniture='Łożko szuflada prawa', position_x='468', position_y='591')
    location20.save()
    location21 = Location.objects.create(room='Gościnny', furniture='Łożko szuflada lewa', position_x='564', position_y='591')
    location21.save()
    location22 = Location.objects.create(room='Komputerowy', furniture='Kallax pojedynczy', position_x='374', position_y='954')
    location22.save()
    location23 = Location.objects.create(room='Komputerowy', furniture='Kallax podwojny', position_x='633', position_y='895')
    location23.save()
    location24 = Location.objects.create(room='Komputerowy', furniture='Kontenerek', position_x='466', position_y='730')
    location24.save()
    location25 = Location.objects.create(room='Komputerowy', furniture='Regał', position_x='452', position_y='900')
    location25.save()
    location26 = Location.objects.create(room='Sypialnia', furniture='Szafa cz.prawa', position_x='466', position_y='1392')
    location26.save()
    location27 = Location.objects.create(room='Sypialnia', furniture='Szafa cz.środkowa', position_x='550', position_y='1392')
    location27.save()
    location28 = Location.objects.create(room='Sypialnia', furniture='Szafa cz.lewa', position_x='627', position_y='1392')
    location28.save()
    location29 = Location.objects.create(room='Sypialnia', furniture='Komoda lewa', position_x='466', position_y='951')
    location29.save()
    location30 = Location.objects.create(room='Sypialnia', furniture='Komoda prawa', position_x='578', position_y='951')
    location30.save()
    location31 = Location.objects.create(room='Sypialnia', furniture='Łóżko str.prawa', position_x='517', position_y='1150')
    location31.save()
    location32 = Location.objects.create(room='Sypialnia', furniture='Łóżko str.lewa', position_x='517', position_y='1278')
    location32.save()
    location33 = Location.objects.create(room='Łazienka', furniture='Szafka', position_x='159', position_y='1151')
    location33.save()
    location34 = Location.objects.create(room='Komórka', furniture='Półki', position_x='198', position_y='1337')
    location34.save()


    # Items
    parasolka = Item.objects.create(name='Parasolka', category='Other')
    parasolka.groups.add(rodzice)
    parasolka.save()
    misio = Item.objects.create(name='Miś', category='Toys')
    misio.groups.add(dzieci)
    misio.save()
    pilka = Item.objects.create(name='Piłka', category='Other')
    pilka.groups.add(rodzice)
    pilka.groups.add(dzieci)
    pilka.save()
