GROUPS = (
    ('Parents', 'Parents'),
    ('Children', 'Children'),
    ('Guests', 'Guests'),
)
CATEGORIES = (
    ('Tools', 'Tools'),
    ('Books', 'Books'),
    ('Computer stuff', 'Computer stuff'),
    ('Clothes', 'Clothes'),
    ('Kitchen', 'Kitchen'),
    ('Bedclothes', 'Bedclothes'),
    ('Holidays', 'Holidays'),
    ('Bathroom', 'Bathroom'),
    ('Car stuff', 'Car stuff'),
    ('Toys', 'Toys'),
    ('Board games', 'Board games'),
    ('Other', 'Other'),
)
LOCATIONS = (
    ('Living room', 'LIV'),
    ('Kitchen', 'KIT'),
    ('Corridor', 'COR'),
    ('Bathroom', 'BAT'),
    ('Guest room', 'GRM'),
    ('Comp room', 'COMP'),
    ('Bedroom', 'BED'),
    ('Storage room', 'STOR'),
)
PLACES = (
    ('Living room - Billy 1', 'LIV1'),
    ('Living room - Billy 2', 'LIV2'),
    ('Living room - Billy 3', 'LIV3'),
    ('Living room - Billy 4', 'LIV4'),
    ('Living room - Billy 5', 'LIV5'),
    ('Living room - Sofa', 'LIVS'),
    ('Kitchen - Cupboard 1', 'KIT1'),
    ('Kitchen - Cupboard 2', 'KIT2'),
    ('Kitchen - Cupboard 3', 'KIT3'),
    ('Kitchen - Cupboard 4', 'KIT4'),
    ('Kitchen - Cupboard 5', 'KIT5'),
    ('Kitchen - Cupboard 6', 'KIT6'),
    ('Kitchen - Cupboard 7', 'KIT7'),
    ('Kitchen - Cupboard 8', 'KIT8'),
    ('Corridor - Wardrobe SingleRight', 'COR1'),
    ('Corridor - Wardrobe Double', 'COR2'),
    ('Corridor - Wardrobe SingleLeft', 'COR3'),
    ('Guest room - Bed drawer Right', 'GRM1'),
    ('Guest room - Bed drawer Left', 'GRM2'),
    ('Guest room - Wardrobe Single', 'GRM1w'),
    ('Guest room - Wardrobe Double', 'GRM2w'),
    ('Computer room - Locker', 'COMP1'),
    ('Computer room - KallaxDouble', 'COMP2'),
    ('Computer room - KallaxSingle', 'COMP3'),
    ('Computer room - Bookcase', 'COMP4'),
    ('Bedroom - Wardrobe DoubleRight', 'BED1'),
    ('Bedroom - Wardrobe Single', 'BED2'),
    ('Bedroom - Wardrobe DoubleLeft', 'BED3'),
    ('Bedroom - ChestOfDrawers Left', 'BED4'),
    ('Bedroom - ChestOfDrawers Right', 'BED5'),
    ('Bedroom - Bed Side Right', 'BED6'),
    ('Bedroom - Bed Side Left', 'BED7'),
    ('Bathroom - Cabinet', 'BAT'),
    ('Storage room', 'STOR'),
)